# fly.toml app configuration file generated for bookshelforganizerbackend on 2023-12-24T21:56:04+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bookshelforganizerbackend"
primary_region = "cdg"

[build]

[[mounts]]
  source = "data"
  destination = "/data"
  auto_extend_size_threshold = 0

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
